#!/bin/bash
# A simple case study script to demonstrate case statement
# Author: Abdallah Saleh Elgholmy
# Date: 30-Nov-2025
# Description: A simple menu driven script using case statement
# Date Modified: 30-Nov-2025

# Clear the screen
clear 

echo Welcome to the simple case study script
echo
echo Please chose one of the options below
echo
echo 'a = Display Date and Time'
echo 'b = List file and directories'
echo 'c = List users logged in'
echo 'd = Check System uptime'
echo

        read choices

        case $choices in

a) date;;
b) ls;;
c) who;;
d) uptime;;
*) echo Invalid choice - Bye.

                esac
