#!/bin/bash
# Author: Abdallah Saleh
# Date: 20-04-2026
# Description: A simple script to count the number of lines in a file.
# Modified: 20-04-2026



for i in {1..10}
do
    echo "This is line number $i"
    sleep 1
done    
